image: node:18

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test_build:
  before_script:
    - npm install
  script:
  - npm run build-dist
  - mv dist public
  rules:
    - if: $CI_COMMIT_BRANCH != "master"
  artifacts:
    paths:
    - public

pages:
  before_script:
    - npm install
  script:
    - npm run build-dist
    - mv dist public
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  artifacts:
    paths:
    - public
